In [6]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
from sklearn import datasets

In [8]:
dataset=datasets.load_iris()

In [9]:
x=dataset["data"]
y=dataset["target"]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=32)

In [14]:
pca=PCA(n_components=3)

In [15]:
x_train=pca.fit_transform(x_train)

In [16]:
x_train


array([[-3.83361362e-01, -3.57175892e-01, -3.20212364e-01],
       [-3.05819129e+00, -4.78789654e-01,  7.62902771e-02],
       [-2.92767856e+00, -9.23726527e-01, -3.71038509e-01],
       [ 2.34445070e+00,  2.91478925e-01,  5.03719765e-01],
       [-9.84114420e-01, -7.50397759e-01, -2.96784542e-02],
       [-2.61396054e+00,  5.10081463e-01,  1.98917295e-01],
       [-2.70027031e+00,  6.14320980e-01, -2.51042644e-01],
       [ 1.45029508e+00, -3.73079020e-01, -1.35492848e-01],
       [ 1.82804982e+00,  4.55657689e-02,  1.79567794e-01],
       [ 2.98545992e-01, -2.91729536e-01,  8.62100467e-02],
       [-2.45902146e+00,  1.34101857e+00,  3.17814975e-01],
       [ 2.54086199e+00,  3.43628021e-01, -1.01704578e-01],
       [-2.67284368e+00,  1.09943885e+00,  1.98065707e-01],
       [ 2.48767486e+00,  2.69142928e-01,  3.00152779e-01],
       [-2.35553865e+00,  7.46576599e-01,  1.97547653e-01],
       [ 3.41230546e+00,  1.16886878e+00,  1.77044925e-01],
       [ 8.43268552e-01, -1.75598766e-01

In [17]:
pca.components_

array([[ 0.36307456, -0.08292207,  0.85472071,  0.36159826],
       [ 0.66730482,  0.71815066, -0.17587596, -0.0896189 ],
       [-0.58307967,  0.62810943,  0.09431747,  0.50655785]])

In [18]:
pca.explained_variance_ratio_

array([0.92421956, 0.05278753, 0.01812923])